#  Problem solving and programming 
##  Day no -13
##  Pv poorna sasidhar
##  16-05-2019 


###  Todays Objectives
* Objective 1
file handling
* Objective 2
data processing

### Problem 1:
##### Problem statement
define a function to read data from a text file
#### Constrains

#### Test Cases
* Test case 1
* Test case 2
* Test case 3

In [18]:
def readFileData(filename):
    #f = open(filename,'r')
    with open(filename,'r') as f:
        #filedata=f.readline()
        #for line in f:
         #   print(line,end='')
    #filedata+=f.readkine
        print(f.read())
    #f.close()
    return 



def writeIntoFile(filename,data,mode):
    with open(filename,mode) as f:
        f.write(data)
    return

writeIntoFile('DataFiles/fileWrite.txt','third line\n','a')

### Problem 2:
##### Problem statement
define a function to generate a marks data file for 1300 students such that each mark is entered in a new line .Marks range from 0 to 100 (inclusive ) as random numbers


In [68]:
import random
def generateMarksData(n,filename):
    with open(filename,'w') as marksfile:
        for i in range(0,n):
            marks = random.randint(0,101)
            marksfile.write(str(marks)+'\n')
        return
generateMarksData(1300,'marksdata.txt')

### Problem 3:
##### Problem statement
Generate a report on the marks data with the following indicators
* Highest mark:
* lowest mark:
* average marks:
* no of students with distinction (>80): 
* no of students with first class(>70): 
* no of students with second class(>60):
* no of students with third class(>40):
* no of students failed(<40):



In [18]:
import timeit
def readfiledata(filename,mode):
    with open(filename,mode) as marksfile:
        start=timeit.default_timer()
        a=[]
        sum=0
        count=0
        b=0
        c=0
        d=0
        e=0
        for i in range(0,1300):
            a.append(int(marksfile.readline()))
        print(max(a)) 
        print(min(a))
        for i in range(0,len(a)):
            sum=sum+a[i]
        average =sum/1300
        print(average)
        for i in range(0,len(a)):
            if(a[i]>=80):
                count=count+1
        
            if(70<=a[i]<80):
                b=b+1
        
            if(60<=a[i]<70):
                c=c+1
       
            if(40<=a[i]<60):
                d=d+1
       
            if(a[i]<40):
                e=e+1
        print('distinction',count)
        print('first class',b)
        print('second class',c)
        print('third class',d)
        print('fail:',e)
        with open('DataFiles/MarksReport.txt','w') as f: 
            f.write('Highest mark : ' + str(max(a)) + '\n')
            f.write('Lowest mark : ' + str(min(a)) + '\n')
            f.write('Average mark : ' + str(average) + '\n')
            f.write('Number of students with distinction : '+ str(count) + '\n')
            f.write('Number of students with first class : '+ str(b) + '\n')
            f.write('Number of students with second class : '+ str(c) + '\n')
            f.write('Number of students with third class : '+ str(d) + '\n')
            f.write('Number of students who failed : '+ str(e) + '\n')
        return timeit.default_timer()-start   
readfiledata('DataFiles/marksdata.txt','r')      

    

101
0
50.70230769230769
distinction 298
first class 124
second class 114
third class 243
fail: 521


0.0067668069998489955

In [1]:
import timeit
def square(n):
    return n*n
st=timeit.default_timer()
li=[1,2,3,4,5,6]
s= list(map(str,li))

s=[float(i) for i in s]
print(timeit.default_timer()-st)
s


In [89]:
li=[3,5,1,6,7,9]

res=sum(1 for i in li if i%2 !=0)
res

5

In [104]:
mark=[3,5,1,6,7,9]
def distinction(mark):
    return mark>=6

dis=sum(map(distinction,mark))


3

## External libraries

In [125]:
import numpy as np
a=np.array([[0,1,2],[3,4,5],[6,7,8]])

print(a)
type(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


numpy.ndarray